Feature history rebase
HydroFish-Waterloo/HydroFish pull request #62
Opened 2024-03-15 14:44 UTC by greatfighter

Merge finished history page to develop branch

2024-03-15 16:04 UTC, marklhj-lee requested changes
Message me if you are confused.

2024-03-15 16:04 UTC, marklhj-lee commented on app/src/main/java/com/hydrofish/app/ui/composables/tabs/HistoryScreen.kt
Move HydroEntry stuff into either utils or some other folder.
Change fetchHydrationData by moving Move Retrofit into ApliClientfile.
After that call can be reduce into val call = ApliClient.apiService.getHydrationData(headers)
You might wanna refactor rest into view model if you get a chance but it's not necessary.

2024-03-15 18:07 UTC, KevinZxy1273 approved these changes
Looks good now

2024-03-15 18:08 UTC, marklhj-lee approved these changes
LGTM

2024-03-15 18:46 UTC, KevinZxy1273 approved these changes
Looks good now

2024-03-17 01:42 UTC, ArthurQiangLi approved these changes
Reviewed

2024-03-17 02:35 UTC, merged